#server:
#  port: 8083
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/patient_db?createDatabaseIfNotExist=true&serverTimezone=UTC
#    username: root
#    password:
#  # Supprimez la section security complètement
#
#  jpa:
#    hibernate.ddl-auto: update
#    properties.hibernate.format_sql: true
#
#  # Ajoutez ceci pour désactiver la sécurité
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#
#clients:
#  doctor:      http://localhost:8082
#  appointment: http://localhost:8083
#  billing:     http://localhost:8084